## Pandas

In [5]:
import pandas as pd

In [7]:
A = pd.Series([2,3,4,5], index = ['a', 'b', 'c', 'd'])

In [8]:
A.values

array([2, 3, 4, 5])

In [9]:
type(A.values)

numpy.ndarray

In [10]:
type(A)

pandas.core.series.Series

In [11]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [12]:
A['a']

np.int64(2)

In [13]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [25]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grads_dict)

In [26]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [27]:
grades.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [21]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [22]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [23]:
marks['A']

np.int64(85)

In [24]:
marks[0:2]

A    85
B    75
dtype: int64

In [28]:
D = pd.DataFrame({'marks':marks,'grades':grades})

In [29]:
D

   marks  grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [30]:
D.T

           A     B     C     D
marks   85.0  75.0  65.0  55.0
grades   4.0   3.5   3.0   2.5

In [31]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [32]:
D.values[2,0]

np.float64(65.0)

In [33]:
D.columns

Index(['marks', 'grades'], dtype='object')

In [36]:
D['ScaledMarks'] = 100*(D['marks']/90)

In [37]:
D

   marks  grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [38]:
del D['ScaledMarks']

In [39]:
D

   marks  grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [41]:
G = D[D['marks'] >70]

In [42]:
G

   marks  grades
A     85     4.0
B     75     3.5

# Pandas NaN

In [51]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [46]:
A

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [45]:
A.fillna(0)

     a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

# implicit and explicit index

In [52]:
A1 = pd.Series(['a','b','c'], index = [1,3,5])

In [53]:
A1[1]

'a'

In [55]:
A1[1:3]

3    b
5    c
dtype: object

In [57]:
A1.loc[1:3]

1    a
3    b
dtype: object

In [59]:
A1.iloc[1:3]

3    b
5    c
dtype: object

In [60]:
D.iloc[2,:]

marks     65.0
grades     3.0
Name: C, dtype: float64

In [61]:
D.iloc[::-1,:]

   marks  grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0