## Pandas

In [1]:
import pandas as pd

In [2]:
A = pd.Series([2,3,4,5], index = ['a', 'b', 'c', 'd'])

In [3]:
A.values

array([2, 3, 4, 5])

In [4]:
type(A.values)

numpy.ndarray

In [5]:
type(A)

pandas.Series

In [6]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [7]:
A['a']

np.int64(2)

In [8]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [11]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grades_dict)

In [12]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [13]:
grades.index

Index(['A', 'B', 'C', 'D'], dtype='str')

In [14]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [15]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [16]:
marks['A']

np.int64(85)

In [17]:
marks[0:2]

A    85
B    75
dtype: int64

In [18]:
D = pd.DataFrame({'marks':marks,'grades':grades})

In [19]:
D

   marks  grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [20]:
D.T

           A     B     C     D
marks   85.0  75.0  65.0  55.0
grades   4.0   3.5   3.0   2.5

In [21]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [22]:
D.values[2,0]

np.float64(65.0)

In [23]:
D.columns

Index(['marks', 'grades'], dtype='str')

In [24]:
D['ScaledMarks'] = 100*(D['marks']/90)

In [25]:
D

   marks  grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [26]:
del D['ScaledMarks']

In [27]:
D

   marks  grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [28]:
G = D[D['marks'] >70]

In [29]:
G

   marks  grades
A     85     4.0
B     75     3.5

# Pandas NaN

In [30]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [31]:
A

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [32]:
A.fillna(0)

     a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

# implicit and explicit index

In [33]:
A1 = pd.Series(['a','b','c'], index = [1,3,5])

In [34]:
A1[1]

'a'

In [35]:
A1[1:3]

3    b
5    c
dtype: str

In [36]:
A1.loc[1:3]

1    a
3    b
dtype: str

In [37]:
A1.iloc[1:3]

3    b
5    c
dtype: str

In [38]:
D.iloc[2,:]

marks     65.0
grades     3.0
Name: C, dtype: float64

In [39]:
D.iloc[::-1,:]

   marks  grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0

In [40]:
from sklearn.impute import SimpleImputer

ModuleNotFoundError: No module named 'sklearn'

In [43]:
df = pd.read_csv('C:/Users/Keenan/Documents/git repos/Python-practice/Pandas/data/covid_19_data.csv')

In [44]:
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [8]:
df.head(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0

In [9]:
df.drop(['SNo','Last Update'], axis = 1, inplace = True)

In [10]:
df.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [11]:
df.rename(columns={'ObservationDate':'Date','Province/State':'Province','Country/Region':'Country'},inplace=True)

In [12]:
df.head()

         Date   Province         Country  Confirmed  Deaths  Recovered
0  01/22/2020      Anhui  Mainland China        1.0     0.0        0.0
1  01/22/2020    Beijing  Mainland China       14.0     0.0        0.0
2  01/22/2020  Chongqing  Mainland China        6.0     0.0        0.0
3  01/22/2020     Fujian  Mainland China        1.0     0.0        0.0
4  01/22/2020      Gansu  Mainland China        0.0     0.0        0.0

In [13]:
df['Date'] = pd.to_datetime(df['Date'])

In [14]:
df.head()

        Date   Province         Country  Confirmed  Deaths  Recovered
0 2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1 2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2 2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3 2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4 2020-01-22      Gansu  Mainland China        0.0     0.0        0.0

In [16]:
df.describe()

,Date,Confirmed,Deaths,Recovered
count,306429,3.064290e+05,306429.000000,3.064290e+05
mean,2020-11-06 01:54:54.146441728,8.567091e+04,2036.403268,5.042029e+04
min,2020-01-22 00:00:00,-3.028440e+05,-178.000000,-8.544050e+05
25%,2020-07-30 00:00:00,1.042000e+03,13.000000,1.100000e+01
50%,2020-11-10 00:00:00,1.037500e+04,192.000000,1.751000e+03
75%,2021-02-18 00:00:00,5.075200e+04,1322.000000,2.027000e+04
max,2021-05-29 00:00:00,5.863138e+06,112385.000000,6.399531e+06
std,NaN,2.775516e+05,6410.938048,2.015124e+05

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       306429 non-null  datetime64[ns]
 1   Province   228326 non-null  object
 2   Country    306429 non-null  object
 3   Confirmed  306429 non-null  float64
 4   Deaths     306429 non-null  float64
 5   Recovered  306429 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 14.0+ MB

In [18]:
df.fillna('NA')

,Date,Province,Country,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1.0,0.0,0.0
1,2020-01-22,Beijing,Mainland China,14.0,0.0,0.0
2,2020-01-22,Chongqing,Mainland China,6.0,0.0,0.0
3,2020-01-22,Fujian,Mainland China,1.0,0.0,0.0
4,2020-01-22,Gansu,Mainland China,0.0,0.0,0.0
...,...,...,...,...,...,...
306424,2021-05-29,Zaporizhia Oblast,Ukraine,102641.0,2335.0,95289.0
306425,2021-05-29,Zeeland,Netherlands,29147.0,245.0,0.0
306426,2021-05-29,Zhejiang,Mainland China,1364.0,1.0,1324.0
306427,2021-05-29,Zhytomyr Oblast,Ukraine,87550.0,1738.0,83790.0
306428,2021-05-29,Zuid-Holland,Netherlands,391559.0,4252.0,0.0

In [1]:
df.info()

NameError: name 'df' is not defined